name: preference_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.0
  flutter_dotenv: ^6.0.0
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Use integration_test from the Flutter SDK (do NOT specify a version on pub)
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/screenshots/
